# Generated by Django 3.1.7 on 2021-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='keg_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='keg_size',
            field=models.PositiveIntegerField(default=88),
            preserve_default=False,
        ),
    ]
