# Generated by Django 3.1.7 on 2021-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20210322_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='keg_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
