# Generated by Django 3.1.7 on 2021-03-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0002_auto_20210322_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_kegs', models.PositiveIntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='beers.beer')),
            ],
        ),
    ]
