# Generated by Django 3.1.7 on 2021-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price_of_keg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
