# Generated by Django 3.1.7 on 2021-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_price_of_keg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='comment',
            new_name='notes',
        ),
    ]
