# Generated by Django 3.1.7 on 2021-03-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210322_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price_of_keg',
        ),
        migrations.AddField(
            model_name='sale',
            name='price_per_keg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
